import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

export default function FAQ() {
  return (
    <section id="faq" className="py-16 bg-white dark:bg-gray-900">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold text-center mb-12 text-gray-800 dark:text-white">Frequently Asked Questions</h2>
        <Accordion type="single" collapsible className="max-w-2xl mx-auto">
          <AccordionItem value="item-1">
            <AccordionTrigger>How secure are the generated secrets?</AccordionTrigger>
            <AccordionContent>
              Our secrets are generated using industry-standard cryptographic functions from the CryptoJS library, ensuring a high level of security and randomness.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger>Can I use these secrets in production?</AccordionTrigger>
            <AccordionContent>
              Yes, the secrets generated by CryptoVault are suitable for production use in Next.js applications. However, always follow best practices for secret management and storage.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger>How should I store the generated secrets?</AccordionTrigger>
            <AccordionContent>
              Store secrets securely using environment variables or a secure secret management system. Never hardcode secrets in your source code or commit them to version control.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger>Is CryptoVault free to use?</AccordionTrigger>
            <AccordionContent>
              Yes, CryptoVault is completely free to use for generating secrets for your Next.js applications.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </section>
  );
}

